# Site Settings
name: iammarco11 blog
description: just my experiences in open source :)
baseurl: ""
url : "https://iammarco11.github.io"

# Blog Settings
theme_settings :
  title : Akshay Praveen Nair -Innovator|Problem Solver|Web Developer
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/dp.jpg
    username : Akshay Praveen Nair
    description : I am a BTech student in Amrita Vishwa Vidyapeetham. My course is core CSE. 
    experience :
      - start : 11-07-2019 
        end : present
        experience : <a href="https://amfoss.in/">amfoss-club</a>
    skills : 
      - skill : HTML5
        value : 75  # Percent value
      - skill : django
        value : 79
      - skill : python
        value : 80
      - skill : c++
        value : 40

  # Icons
  icons :
    email:  akshaypraveennair11@gmail.com
    linkedin:  # Full URL 
    github: iammarco11
    gitlab: iammarco11
    bitbucket: 
    google_plus:
    twitter: akshaay_11
    youtube:
    facebook: 
    instagram: akshaay.11

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
