# Site Settings
baseurl: ""
url : "https://iammarco11.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/dp.jpg
    username : akshay
    description : I am a BTech student in Amrita Vishwa Vidyapeetham. My course is core CSE. 
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5, CSS
        value : 75  # Percent value
      - skill : django
        value : 79
      - skill : python
        value : 80
  # Icons
  icons :
    email:  akshaypraveennair11@gmail.com
    linkedin:  # Full URL 
    github: iammarco11
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: akshaay_11
    youtube:
    facebook: 
    instagram: akshaay.11

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
